<?xml version="1.0"?>
<!--
 ===========================================================================
   Copyright 2002-2010 Martin Dvorak

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 ===========================================================================
-->
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:strip-space elements="*"/>
  <xsl:output method="xml" indent="yes"/>

    <xsl:template match="/">
        <xsl:apply-templates select="resource/data/conceptTreeProperty">
        </xsl:apply-templates>
    </xsl:template>
    
    <xsl:template match="resource/data/conceptTreeProperty">
      <rdf:RDF
        xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
        xmlns:skos="http://www.w3.org/2004/02/skos/core#"
        xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">

        <skos:Concept rdf:about="{./resource/metadata/uri/text()}">        
          <skos:prefLabel><xsl:value-of select="./resource/data/labelProperty/text()"/></skos:prefLabel>
          <skos:definition>
          <skos:narrower>
            <skos:OrderedCollection>
              <rdfs:label>people by age</rdfs:label>
              <skos:memberList rdf:parseType="Collection">
                <skos:Concept rdf:about="http://www.example.com/concepts#infants"/>
                <skos:Concept rdf:about="http://www.example.com/concepts#children"/>
                <skos:Concept rdf:about="http://www.example.com/concepts#adults"/>
              </skos:memberList>
            </skos:OrderedCollection>
          </skos:narrower>
        </skos:Concept>

      </rdf:RDF>






      <opml version="1.1">
      <head>
         <title>OPML generated by MindRaider (http://mindraider.sourceforge.net)</title>
         <!--
         <dateCreated>23.4.05 11:15</dateCreated>
         <ownerName>dvorka</ownerName>
         -->
       </head>

       <body>    
        <outline>
         <xsl:attribute name="title">
           <xsl:value-of select="./resource/data/labelProperty/text()"/>
         </xsl:attribute>
         <xsl:attribute name="text">
           <xsl:value-of select="./resource/data/labelProperty/text()"/>
         </xsl:attribute>

           <xsl:apply-templates select="conceptTreeProperty">
           </xsl:apply-templates>

        </outline>
       </body>
      </opml>

    </xsl:template>



    <xsl:template match="conceptTreeProperty">
         <outline>
           <xsl:attribute name="title">
             <xsl:value-of select="./resource/data/labelProperty/text()"/>
           </xsl:attribute>
           <xsl:attribute name="text">
             <xsl:value-of select="./resource/data/labelProperty/text()"/>
           </xsl:attribute>
           <xsl:attribute name="xmlUrl">
             <xsl:value-of select="./resource/metadata/uri/text()"/>
           </xsl:attribute>
           <!-- TODO: add attachments in here in the future -->

         <outline>
           <xsl:attribute name="title">
             <xsl:value-of select="./resource/data/labelProperty/text()"/>
           </xsl:attribute>
           <xsl:attribute name="text">
             <xsl:value-of select="./resource/data/annotationProperty/text()"/>
           </xsl:attribute>
           <xsl:attribute name="description">
             <xsl:value-of select="./resource/data/annotationProperty/text()"/>
           </xsl:attribute>
           <xsl:attribute name="xmlUrl">
             <xsl:value-of select="./resource/metadata/uri/text()"/>
           </xsl:attribute>
           <xsl:attribute name="isComment">
             <xsl:value-of select="'true'"/>
           </xsl:attribute>
         </outline>

           <xsl:apply-templates select="./conceptTreeProperty">
           </xsl:apply-templates>

         </outline>

    </xsl:template>

</xsl:stylesheet>